// Copyright 2024-2026 The PRECINCT Authors
// SPDX-License-Identifier: Apache-2.0

package mcpgateway

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// --- Unit Tests: Construction ---

func TestNewClient_Defaults(t *testing.T) {
	c := NewClient("http://localhost:9090", "spiffe://test/agent")

	if c.url != "http://localhost:9090" {
		t.Errorf("url = %q, want %q", c.url, "http://localhost:9090")
	}
	if c.spiffeID != "spiffe://test/agent" {
		t.Errorf("spiffeID = %q, want %q", c.spiffeID, "spiffe://test/agent")
	}
	if c.sessionID == "" {
		t.Error("sessionID should be auto-generated, got empty string")
	}
	if c.maxRetries != DefaultMaxRetries {
		t.Errorf("maxRetries = %d, want %d", c.maxRetries, DefaultMaxRetries)
	}
	if c.backoffBase != DefaultBackoffBase {
		t.Errorf("backoffBase = %v, want %v", c.backoffBase, DefaultBackoffBase)
	}
	if c.timeout != DefaultTimeout {
		t.Errorf("timeout = %v, want %v", c.timeout, DefaultTimeout)
	}
}

func TestNewClient_WithSessionID(t *testing.T) {
	c := NewClient("http://localhost:9090", "spiffe://test", WithSessionID("my-session"))
	if c.sessionID != "my-session" {
		t.Errorf("sessionID = %q, want %q", c.sessionID, "my-session")
	}
}

func TestNewClient_SessionIDAccessor(t *testing.T) {
	c := NewClient("http://localhost:9090", "spiffe://test", WithSessionID("sess-42"))
	if c.SessionID() != "sess-42" {
		t.Errorf("SessionID() = %q, want %q", c.SessionID(), "sess-42")
	}
}

func TestNewClient_AutoGeneratedSessionID_IsUUID(t *testing.T) {
	c := NewClient("http://localhost:9090", "spiffe://test")
	// UUID v4 format: 8-4-4-4-12 hex chars
	parts := strings.Split(c.sessionID, "-")
	if len(parts) != 5 {
		t.Errorf("sessionID %q does not look like a UUID", c.sessionID)
	}
}

func TestNewClient_WithOptions(t *testing.T) {
	c := NewClient(
		"http://gw:8080",
		"spiffe://x",
		WithTimeout(5*time.Second),
		WithMaxRetries(1),
		WithBackoffBase(100*time.Millisecond),
	)
	if c.timeout != 5*time.Second {
		t.Errorf("timeout = %v, want %v", c.timeout, 5*time.Second)
	}
	if c.maxRetries != 1 {
		t.Errorf("maxRetries = %d, want %d", c.maxRetries, 1)
	}
	if c.backoffBase != 100*time.Millisecond {
		t.Errorf("backoffBase = %v, want %v", c.backoffBase, 100*time.Millisecond)
	}
}

func TestCallModelChat_HeadersAndEndpoint(t *testing.T) {
	var gotPath string
	var gotAuth string
	var gotProvider string
	var gotPurpose string
	var gotMissionMode string
	var gotAllowedIntents string
	var gotAllowedTopics string
	var gotBlockedTopics string
	var gotOutOfScopeAction string
	var gotPayload map[string]any

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotProvider = r.Header.Get("X-Model-Provider")
		gotPurpose = r.Header.Get("X-Agent-Purpose")
		gotMissionMode = r.Header.Get("X-Mission-Boundary-Mode")
		gotAllowedIntents = r.Header.Get("X-Mission-Allowed-Intents")
		gotAllowedTopics = r.Header.Get("X-Mission-Allowed-Topics")
		gotBlockedTopics = r.Header.Get("X-Mission-Blocked-Topics")
		gotOutOfScopeAction = r.Header.Get("X-Mission-Out-Of-Scope-Action")
		if err := json.NewDecoder(r.Body).Decode(&gotPayload); err != nil {
			t.Fatalf("decode request: %v", err)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"id":"chatcmpl-1","choices":[{"index":0}]}`))
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test/agent", WithSessionID("sess-model"), WithHTTPClient(srv.Client()))
	resp, err := c.CallModelChat(context.Background(), ModelChatRequest{
		Model:               "llama-3.3-70b-versatile",
		Messages:            []map[string]any{{"role": "user", "content": "hello"}},
		Provider:            "groq",
		APIKeyRef:           "Bearer $SPIKE{ref:deadbeef,exp:3600}",
		AgentPurpose:        "restaurant_order_support",
		MissionBoundaryMode: "enforce",
		AllowedIntents:      []string{"place_order", "order_status"},
		AllowedTopics:       []string{"order", "menu"},
		BlockedTopics:       []string{"python", "linked list"},
		OutOfScopeAction:    "rewrite",
		ExtraPayload:        map[string]any{"temperature": 0.1},
	})
	if err != nil {
		t.Fatalf("CallModelChat failed: %v", err)
	}
	if resp["id"] != "chatcmpl-1" {
		t.Fatalf("unexpected response: %#v", resp)
	}
	if gotPath != "/openai/v1/chat/completions" {
		t.Fatalf("path=%q want=/openai/v1/chat/completions", gotPath)
	}
	if gotProvider != "groq" {
		t.Fatalf("provider header=%q want=groq", gotProvider)
	}
	if gotAuth != "Bearer $SPIKE{ref:deadbeef,exp:3600}" {
		t.Fatalf("authorization header mismatch: %q", gotAuth)
	}
	if gotPurpose != "restaurant_order_support" {
		t.Fatalf("agent purpose header=%q want=restaurant_order_support", gotPurpose)
	}
	if gotMissionMode != "enforce" {
		t.Fatalf("mission mode header=%q want=enforce", gotMissionMode)
	}
	if gotAllowedIntents != "place_order,order_status" {
		t.Fatalf("allowed intents header=%q", gotAllowedIntents)
	}
	if gotAllowedTopics != "order,menu" {
		t.Fatalf("allowed topics header=%q", gotAllowedTopics)
	}
	if gotBlockedTopics != "python,linked list" {
		t.Fatalf("blocked topics header=%q", gotBlockedTopics)
	}
	if gotOutOfScopeAction != "rewrite" {
		t.Fatalf("out-of-scope action header=%q want=rewrite", gotOutOfScopeAction)
	}
	if gotPayload["model"] != "llama-3.3-70b-versatile" {
		t.Fatalf("payload model mismatch: %#v", gotPayload["model"])
	}
}

func TestCallModelChat_RelativeEndpointsStayOnGateway(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		endpoint string
		wantPath string
	}{
		{
			name:     "leading slash",
			endpoint: "/model/v1/chat/completions",
			wantPath: "/model/v1/chat/completions",
		},
		{
			name:     "no leading slash",
			endpoint: "model/v1/chat/completions",
			wantPath: "/model/v1/chat/completions",
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var gotPath string
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				gotPath = r.URL.Path
				w.Header().Set("Content-Type", "application/json")
				_, _ = w.Write([]byte(`{"id":"chatcmpl-2","choices":[{"index":0}]}`))
			}))
			defer srv.Close()

			c := NewClient(srv.URL, "spiffe://test/agent", WithHTTPClient(srv.Client()))
			_, err := c.CallModelChat(context.Background(), ModelChatRequest{
				Model:    "llama-3.3-70b-versatile",
				Messages: []map[string]any{{"role": "user", "content": "hello"}},
				Endpoint: tt.endpoint,
			})
			if err != nil {
				t.Fatalf("CallModelChat failed: %v", err)
			}
			if gotPath != tt.wantPath {
				t.Fatalf("path=%q want=%q", gotPath, tt.wantPath)
			}
		})
	}
}

func TestCallModelChat_DenialParsesGatewayError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusForbidden)
		_, _ = w.Write([]byte(`{"code":"authz_policy_denied","message":"denied","middleware":"opa_policy","middleware_step":6}`))
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test/agent", WithHTTPClient(srv.Client()))
	_, err := c.CallModelChat(context.Background(), ModelChatRequest{
		Model:    "llama-3.3-70b-versatile",
		Messages: []map[string]any{{"role": "user", "content": "hello"}},
	})
	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected GatewayError, got %T (%v)", err, err)
	}
	if ge.HTTPStatus != http.StatusForbidden {
		t.Fatalf("status=%d want=403", ge.HTTPStatus)
	}
	if ge.Code != "authz_policy_denied" {
		t.Fatalf("code=%q want=authz_policy_denied", ge.Code)
	}
}

func TestCallModelChat_RejectsAbsoluteEndpoints(t *testing.T) {
	c := NewClient("http://localhost:9090", "spiffe://test/agent")
	_, err := c.CallModelChat(context.Background(), ModelChatRequest{
		Model:    "llama-3.3-70b-versatile",
		Messages: []map[string]any{{"role": "user", "content": "hello"}},
		Endpoint: "https://api.openai.com/v1/chat/completions",
	})
	if err == nil {
		t.Fatal("expected absolute endpoint to be rejected")
	}
	if !strings.Contains(err.Error(), "gateway-relative endpoints") {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- Unit Tests: JSON-RPC Envelope Construction ---

func TestCall_JSONRPCEnvelope(t *testing.T) {
	var received jsonRPCRequest
	var headers http.Header

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		headers = r.Header.Clone()
		if err := json.NewDecoder(r.Body).Decode(&received); err != nil {
			t.Errorf("failed to decode request body: %v", err)
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  map[string]any{"data": "ok"},
			ID:      float64(received.ID),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test/agent",
		WithSessionID("sess-abc"),
		WithHTTPClient(srv.Client()),
	)

	_, err := c.Call(context.Background(), "tavily_search", map[string]any{
		"query":       "AI security",
		"max_results": 5,
	})
	if err != nil {
		t.Fatalf("Call failed: %v", err)
	}

	// Verify JSON-RPC fields
	if received.JSONRPC != "2.0" {
		t.Errorf("jsonrpc = %q, want %q", received.JSONRPC, "2.0")
	}
	if received.Method != "tools/call" {
		t.Errorf("method = %q, want %q", received.Method, "tools/call")
	}
	if received.Params["name"] != "tavily_search" {
		t.Errorf("params.name = %v, want %q", received.Params["name"], "tavily_search")
	}
	args, ok := received.Params["arguments"].(map[string]any)
	if !ok {
		t.Fatalf("params.arguments missing or wrong type: %#v", received.Params["arguments"])
	}
	if args["query"] != "AI security" {
		t.Errorf("params.arguments.query = %v, want %q", args["query"], "AI security")
	}
	if received.ID <= 0 {
		t.Errorf("id should be > 0, got %d", received.ID)
	}

	// Verify headers
	if ct := headers.Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/json")
	}
	if sid := headers.Get("X-SPIFFE-ID"); sid != "spiffe://test/agent" {
		t.Errorf("X-SPIFFE-ID = %q, want %q", sid, "spiffe://test/agent")
	}
	if ssid := headers.Get("X-Session-ID"); ssid != "sess-abc" {
		t.Errorf("X-Session-ID = %q, want %q", ssid, "sess-abc")
	}
}

func TestCall_IncrementingRequestIDs(t *testing.T) {
	var ids []int64

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var req jsonRPCRequest
		json.NewDecoder(r.Body).Decode(&req)
		ids = append(ids, req.ID)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  "ok",
			ID:      float64(req.ID),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))

	for i := 0; i < 3; i++ {
		if _, err := c.Call(context.Background(), "test_tool", nil); err != nil {
			t.Fatalf("Call %d failed: %v", i, err)
		}
	}

	if len(ids) != 3 {
		t.Fatalf("expected 3 IDs, got %d", len(ids))
	}
	for i := 1; i < len(ids); i++ {
		if ids[i] <= ids[i-1] {
			t.Errorf("IDs not strictly increasing: %v", ids)
		}
	}
}

// --- Unit Tests: Error Parsing ---

func TestCall_ParsesGatewayErrorFromJSON(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(403)
		json.NewEncoder(w).Encode(GatewayError{
			Code:        "authz_policy_denied",
			Message:     "OPA policy denied access",
			Middleware:  "opa",
			Step:        6,
			DecisionID:  "dec-123",
			TraceID:     "trace-456",
			Remediation: "Add a grant for this tool",
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	_, err := c.Call(context.Background(), "blocked_tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}

	if ge.Code != "authz_policy_denied" {
		t.Errorf("Code = %q, want %q", ge.Code, "authz_policy_denied")
	}
	if ge.Message != "OPA policy denied access" {
		t.Errorf("Message = %q, want %q", ge.Message, "OPA policy denied access")
	}
	if ge.Middleware != "opa" {
		t.Errorf("Middleware = %q, want %q", ge.Middleware, "opa")
	}
	if ge.Step != 6 {
		t.Errorf("Step = %d, want %d", ge.Step, 6)
	}
	if ge.DecisionID != "dec-123" {
		t.Errorf("DecisionID = %q, want %q", ge.DecisionID, "dec-123")
	}
	if ge.TraceID != "trace-456" {
		t.Errorf("TraceID = %q, want %q", ge.TraceID, "trace-456")
	}
	if ge.HTTPStatus != 403 {
		t.Errorf("HTTPStatus = %d, want %d", ge.HTTPStatus, 403)
	}
	if ge.Remediation != "Add a grant for this tool" {
		t.Errorf("Remediation = %q, want %q", ge.Remediation, "Add a grant for this tool")
	}
}

func TestCall_ParsesNonJSONError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(500)
		w.Write([]byte("Internal Server Error"))
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	_, err := c.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}
	if ge.Code != "unknown" {
		t.Errorf("Code = %q, want %q", ge.Code, "unknown")
	}
	if ge.HTTPStatus != 500 {
		t.Errorf("HTTPStatus = %d, want %d", ge.HTTPStatus, 500)
	}
	if !strings.Contains(ge.Message, "Internal Server Error") {
		t.Errorf("Message should contain response text, got %q", ge.Message)
	}
}

func TestCall_ParsesJSONRPCError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"error":   map[string]any{"code": -32600, "message": "Invalid Request"},
			"id":      1,
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	_, err := c.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}
	if ge.Code != "jsonrpc_error" {
		t.Errorf("Code = %q, want %q", ge.Code, "jsonrpc_error")
	}
	if !strings.Contains(ge.Message, "Invalid Request") {
		t.Errorf("Message should contain error text, got %q", ge.Message)
	}
}

func TestCall_ParsesInvalidJSONResponse(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte("not json at all"))
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	_, err := c.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}
	if ge.Code != "invalid_response" {
		t.Errorf("Code = %q, want %q", ge.Code, "invalid_response")
	}
}

// --- Unit Tests: Retry Logic ---

func TestCall_Retries503WithExponentialBackoff(t *testing.T) {
	var attempts atomic.Int32

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		n := attempts.Add(1)
		if n <= 2 {
			// First 2 attempts return 503
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(503)
			json.NewEncoder(w).Encode(GatewayError{
				Code:    "circuit_open",
				Message: "Circuit breaker is open",
			})
			return
		}
		// 3rd attempt succeeds
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  map[string]any{"status": "ok"},
			ID:      float64(1),
		})
	}))
	defer srv.Close()

	var sleepDurations []time.Duration
	c := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		WithMaxRetries(3),
		WithBackoffBase(100*time.Millisecond),
		withSleepFunc(func(d time.Duration) { sleepDurations = append(sleepDurations, d) }),
	)

	result, err := c.Call(context.Background(), "tool", nil)
	if err != nil {
		t.Fatalf("Call failed: %v", err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}

	// Should have attempted 3 times (2 retries + 1 success)
	if got := attempts.Load(); got != 3 {
		t.Errorf("attempts = %d, want 3", got)
	}

	// Should have slept twice (between attempt 1->2 and 2->3)
	if len(sleepDurations) != 2 {
		t.Fatalf("sleep count = %d, want 2", len(sleepDurations))
	}

	// Exponential: 100ms, 200ms
	if sleepDurations[0] != 100*time.Millisecond {
		t.Errorf("sleep[0] = %v, want %v", sleepDurations[0], 100*time.Millisecond)
	}
	if sleepDurations[1] != 200*time.Millisecond {
		t.Errorf("sleep[1] = %v, want %v", sleepDurations[1], 200*time.Millisecond)
	}
}

func TestCall_ExhaustsRetriesOn503(t *testing.T) {
	var attempts atomic.Int32

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempts.Add(1)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(503)
		json.NewEncoder(w).Encode(GatewayError{
			Code:    "circuit_open",
			Message: "Circuit breaker is open",
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		WithMaxRetries(3),
		WithBackoffBase(1*time.Millisecond),
		withSleepFunc(func(d time.Duration) {}), // no-op sleep for speed
	)

	_, err := c.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}
	if ge.Code != "circuit_open" {
		t.Errorf("Code = %q, want %q", ge.Code, "circuit_open")
	}
	if ge.HTTPStatus != 503 {
		t.Errorf("HTTPStatus = %d, want %d", ge.HTTPStatus, 503)
	}

	// initial + 3 retries = 4 total attempts
	if got := attempts.Load(); got != 4 {
		t.Errorf("attempts = %d, want 4 (initial + 3 retries)", got)
	}
}

func TestCall_DoesNotRetry403(t *testing.T) {
	var attempts atomic.Int32

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempts.Add(1)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(403)
		json.NewEncoder(w).Encode(GatewayError{
			Code:    "authz_policy_denied",
			Message: "Access denied",
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		WithMaxRetries(3),
		withSleepFunc(func(d time.Duration) { t.Error("should not sleep for non-503") }),
	)

	_, err := c.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}
	if ge.HTTPStatus != 403 {
		t.Errorf("HTTPStatus = %d, want %d", ge.HTTPStatus, 403)
	}

	// Should NOT retry -- only 1 attempt
	if got := attempts.Load(); got != 1 {
		t.Errorf("attempts = %d, want 1 (no retry for 403)", got)
	}
}

func TestCall_RespectsContextCancellation(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(503)
		json.NewEncoder(w).Encode(GatewayError{Code: "circuit_open"})
	}))
	defer srv.Close()

	ctx, cancel := context.WithCancel(context.Background())

	c := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		WithMaxRetries(10),
		WithBackoffBase(time.Second),
		withSleepFunc(func(d time.Duration) {
			// Cancel context during first backoff sleep
			cancel()
			// Give a moment for the select to pick up cancellation
			time.Sleep(10 * time.Millisecond)
		}),
	)

	_, err := c.Call(ctx, "tool", nil)
	if err == nil {
		t.Fatal("expected error from cancelled context")
	}
	if !errors.Is(err, context.Canceled) {
		// It could be context.Canceled or a GatewayError depending on timing
		// Either is acceptable as long as we don't hang forever
		var ge *GatewayError
		if !errors.As(err, &ge) {
			t.Errorf("expected context.Canceled or *GatewayError, got %T: %v", err, err)
		}
	}
}

// --- Integration Tests: httptest server simulating realistic gateway ---

func TestIntegration_SuccessfulToolCall(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Verify request shape
		if r.Method != http.MethodPost {
			t.Errorf("method = %q, want POST", r.Method)
		}
		if ct := r.Header.Get("Content-Type"); ct != "application/json" {
			t.Errorf("Content-Type = %q, want application/json", ct)
		}
		if sid := r.Header.Get("X-SPIFFE-ID"); sid == "" {
			t.Error("X-SPIFFE-ID header missing")
		}
		if ssid := r.Header.Get("X-Session-ID"); ssid == "" {
			t.Error("X-Session-ID header missing")
		}

		var req jsonRPCRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			t.Fatalf("decode request: %v", err)
		}

		// Return a realistic JSON-RPC response
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"id":      req.ID,
			"result": map[string]any{
				"content": []map[string]any{
					{
						"type": "text",
						"text": "Search results for AI security...",
					},
				},
			},
		})
	}))
	defer srv.Close()

	client := NewClient(srv.URL, "spiffe://poc.local/agents/test/dev",
		WithHTTPClient(srv.Client()),
		WithSessionID("test-session-123"),
	)

	result, err := client.Call(context.Background(), "tavily_search", map[string]any{
		"query":       "AI security",
		"max_results": 5,
	})
	if err != nil {
		t.Fatalf("Call failed: %v", err)
	}

	// Verify we got the result back
	resultMap, ok := result.(map[string]any)
	if !ok {
		t.Fatalf("result type = %T, want map[string]any", result)
	}
	content, ok := resultMap["content"]
	if !ok {
		t.Fatal("result missing 'content' field")
	}
	contentSlice, ok := content.([]any)
	if !ok {
		t.Fatalf("content type = %T, want []any", content)
	}
	if len(contentSlice) != 1 {
		t.Fatalf("content length = %d, want 1", len(contentSlice))
	}
}

func TestIntegration_DenialWithFullEnvelope(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(403)
		json.NewEncoder(w).Encode(map[string]any{
			"code":            "authz_policy_denied",
			"message":         "OPA policy denied tool access for agent",
			"middleware":      "opa",
			"middleware_step": 6,
			"decision_id":     "dec-abc-123",
			"trace_id":        "4bf92f3577b34da6a3ce929d0e0e4736",
			"details":         map[string]any{"policy": "data.gateway.allow", "input_tool": "bash"},
			"remediation":     "Add a grant in policies/grants.yaml for this agent+tool pair",
			"docs_url":        "https://docs.example.com/gateway/authz",
		})
	}))
	defer srv.Close()

	client := NewClient(srv.URL, "spiffe://poc.local/agents/test/dev",
		WithHTTPClient(srv.Client()),
	)

	_, err := client.Call(context.Background(), "bash", map[string]any{"command": "echo hello"})

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}

	// Verify every field of the unified envelope
	if ge.Code != "authz_policy_denied" {
		t.Errorf("Code = %q, want %q", ge.Code, "authz_policy_denied")
	}
	if ge.Message != "OPA policy denied tool access for agent" {
		t.Errorf("Message = %q, want %q", ge.Message, "OPA policy denied tool access for agent")
	}
	if ge.Middleware != "opa" {
		t.Errorf("Middleware = %q, want %q", ge.Middleware, "opa")
	}
	if ge.Step != 6 {
		t.Errorf("Step = %d, want %d", ge.Step, 6)
	}
	if ge.DecisionID != "dec-abc-123" {
		t.Errorf("DecisionID = %q, want %q", ge.DecisionID, "dec-abc-123")
	}
	if ge.TraceID != "4bf92f3577b34da6a3ce929d0e0e4736" {
		t.Errorf("TraceID = %q, want %q", ge.TraceID, "4bf92f3577b34da6a3ce929d0e0e4736")
	}
	if ge.HTTPStatus != 403 {
		t.Errorf("HTTPStatus = %d, want %d", ge.HTTPStatus, 403)
	}
	if ge.Remediation != "Add a grant in policies/grants.yaml for this agent+tool pair" {
		t.Errorf("Remediation = %q", ge.Remediation)
	}
	if ge.DocsURL != "https://docs.example.com/gateway/authz" {
		t.Errorf("DocsURL = %q", ge.DocsURL)
	}
	if ge.Details["policy"] != "data.gateway.allow" {
		t.Errorf("Details.policy = %v", ge.Details["policy"])
	}
}

func TestIntegration_503RetryThenSuccess(t *testing.T) {
	var attempts atomic.Int32

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		n := attempts.Add(1)
		if n == 1 {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(503)
			json.NewEncoder(w).Encode(map[string]any{
				"code":            "circuit_open",
				"message":         "Circuit breaker is open",
				"middleware":      "circuit_breaker",
				"middleware_step": 12,
			})
			return
		}

		var req jsonRPCRequest
		json.NewDecoder(r.Body).Decode(&req)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"id":      req.ID,
			"result":  map[string]any{"data": "recovered"},
		})
	}))
	defer srv.Close()

	client := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		WithMaxRetries(3),
		WithBackoffBase(1*time.Millisecond),
		withSleepFunc(func(d time.Duration) {}),
	)

	result, err := client.Call(context.Background(), "tool", nil)
	if err != nil {
		t.Fatalf("Call failed after retry: %v", err)
	}

	resultMap, ok := result.(map[string]any)
	if !ok {
		t.Fatalf("result type = %T, want map", result)
	}
	if resultMap["data"] != "recovered" {
		t.Errorf("result.data = %v, want 'recovered'", resultMap["data"])
	}

	if got := attempts.Load(); got != 2 {
		t.Errorf("attempts = %d, want 2", got)
	}
}

func TestIntegration_SessionIDAutoGenerated(t *testing.T) {
	var receivedSessionIDs []string

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		receivedSessionIDs = append(receivedSessionIDs, r.Header.Get("X-Session-ID"))
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  "ok",
			ID:      float64(1),
		})
	}))
	defer srv.Close()

	// Two clients should get different auto-generated session IDs
	c1 := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	c2 := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))

	c1.Call(context.Background(), "tool", nil)
	c2.Call(context.Background(), "tool", nil)

	if len(receivedSessionIDs) != 2 {
		t.Fatalf("expected 2 requests, got %d", len(receivedSessionIDs))
	}

	// Both should be non-empty
	if receivedSessionIDs[0] == "" || receivedSessionIDs[1] == "" {
		t.Error("session IDs should be non-empty")
	}

	// They should be different (auto-generated UUIDs)
	if receivedSessionIDs[0] == receivedSessionIDs[1] {
		t.Error("two clients should have different auto-generated session IDs")
	}
}

func TestIntegration_SessionIDConsistentAcrossCalls(t *testing.T) {
	var receivedSessionIDs []string

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		receivedSessionIDs = append(receivedSessionIDs, r.Header.Get("X-Session-ID"))
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  "ok",
			ID:      float64(1),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))

	// Multiple calls from same client should use same session ID
	c.Call(context.Background(), "tool1", nil)
	c.Call(context.Background(), "tool2", nil)

	if len(receivedSessionIDs) != 2 {
		t.Fatalf("expected 2 requests, got %d", len(receivedSessionIDs))
	}

	if receivedSessionIDs[0] != receivedSessionIDs[1] {
		t.Error("same client should send same session ID across calls")
	}
}

func TestIntegration_DLPDenialWithDetails(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(403)
		json.NewEncoder(w).Encode(map[string]any{
			"code":            "dlp_credentials_detected",
			"message":         "Request body contains potential credentials",
			"middleware":      "dlp",
			"middleware_step": 7,
			"decision_id":     "dec-dlp-001",
			"trace_id":        "abc123",
			"details": map[string]any{
				"patterns_matched": []string{"AWS_SECRET_ACCESS_KEY"},
			},
			"remediation": "Remove credentials from the request parameters",
		})
	}))
	defer srv.Close()

	client := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	_, err := client.Call(context.Background(), "write", map[string]any{
		"content": "AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE",
	})

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}

	if ge.Code != "dlp_credentials_detected" {
		t.Errorf("Code = %q, want dlp_credentials_detected", ge.Code)
	}
	if ge.Middleware != "dlp" {
		t.Errorf("Middleware = %q, want dlp", ge.Middleware)
	}
	if ge.Step != 7 {
		t.Errorf("Step = %d, want 7", ge.Step)
	}
	if ge.Details == nil {
		t.Fatal("Details should not be nil")
	}
}

func TestIntegration_RateLimitDenial(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(429)
		json.NewEncoder(w).Encode(map[string]any{
			"code":            "ratelimit_exceeded",
			"message":         "Rate limit exceeded for this agent",
			"middleware":      "rate_limiter",
			"middleware_step": 11,
			"decision_id":     "dec-rl-001",
			"trace_id":        "xyz789",
		})
	}))
	defer srv.Close()

	client := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		withSleepFunc(func(d time.Duration) { t.Error("should not retry 429") }),
	)

	_, err := client.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}

	if ge.Code != "ratelimit_exceeded" {
		t.Errorf("Code = %q, want ratelimit_exceeded", ge.Code)
	}
	if ge.HTTPStatus != 429 {
		t.Errorf("HTTPStatus = %d, want 429", ge.HTTPStatus)
	}
}

func TestIntegration_AuthDenial(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(401)
		json.NewEncoder(w).Encode(map[string]any{
			"code":            "auth_invalid_identity",
			"message":         "SPIFFE ID not in trust domain",
			"middleware":      "spiffe_auth",
			"middleware_step": 3,
			"decision_id":     "dec-auth-001",
			"trace_id":        "trace-auth",
			"remediation":     "Use a valid SPIFFE ID in the trust domain",
		})
	}))
	defer srv.Close()

	client := NewClient(srv.URL, "spiffe://wrong-domain/agent", WithHTTPClient(srv.Client()))
	_, err := client.Call(context.Background(), "tool", nil)

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}

	if ge.Code != "auth_invalid_identity" {
		t.Errorf("Code = %q, want auth_invalid_identity", ge.Code)
	}
	if ge.HTTPStatus != 401 {
		t.Errorf("HTTPStatus = %d, want 401", ge.HTTPStatus)
	}
	if ge.Middleware != "spiffe_auth" {
		t.Errorf("Middleware = %q, want spiffe_auth", ge.Middleware)
	}
}

// --- Unit Tests: CallWithMetadata ---

func TestCallWithMetadata_ReturnsResponseMeta(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Precinct-Reversibility", "irreversible")
		w.Header().Set("X-Precinct-Backup-Recommended", "true")
		w.Header().Set("X-Precinct-Principal-Level", "1")
		w.Header().Set("X-Precinct-Principal-Role", "owner")
		w.Header().Set("X-Precinct-Principal-Capabilities", "read,write,delete")
		w.Header().Set("X-Precinct-Auth-Method", "mtls_svid")
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  map[string]any{"status": "ok"},
			ID:      float64(1),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test/owner/alice", WithHTTPClient(srv.Client()))
	cr, err := c.CallWithMetadata(context.Background(), "delete_resource", map[string]any{"id": "abc"})
	if err != nil {
		t.Fatalf("CallWithMetadata failed: %v", err)
	}

	if cr.Meta.Reversibility != "irreversible" {
		t.Errorf("Reversibility = %q, want %q", cr.Meta.Reversibility, "irreversible")
	}
	if !cr.Meta.BackupRecommended {
		t.Error("BackupRecommended should be true")
	}
	if cr.Meta.PrincipalLevel != 1 {
		t.Errorf("PrincipalLevel = %d, want 1", cr.Meta.PrincipalLevel)
	}
	if cr.Meta.PrincipalRole != "owner" {
		t.Errorf("PrincipalRole = %q, want %q", cr.Meta.PrincipalRole, "owner")
	}
	if len(cr.Meta.PrincipalCapabilities) != 3 {
		t.Errorf("PrincipalCapabilities = %v, want 3 items", cr.Meta.PrincipalCapabilities)
	}
	if cr.Meta.AuthMethod != "mtls_svid" {
		t.Errorf("AuthMethod = %q, want %q", cr.Meta.AuthMethod, "mtls_svid")
	}

	// Result should still be accessible
	resultMap, ok := cr.Result.(map[string]any)
	if !ok {
		t.Fatalf("Result type = %T, want map", cr.Result)
	}
	if resultMap["status"] != "ok" {
		t.Errorf("Result.status = %v, want 'ok'", resultMap["status"])
	}
}

func TestCallWithMetadata_ErrorIncludesResponseMeta(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Precinct-Reversibility", "irreversible")
		w.Header().Set("X-Precinct-Backup-Recommended", "true")
		w.Header().Set("X-Precinct-Principal-Level", "4")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(403)
		json.NewEncoder(w).Encode(GatewayError{
			Code:    "irreversible_action_denied",
			Message: "Irreversible action denied for external principal",
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test/external/bob", WithHTTPClient(srv.Client()))
	_, err := c.CallWithMetadata(context.Background(), "delete_resource", map[string]any{"id": "abc"})

	var ge *GatewayError
	if !errors.As(err, &ge) {
		t.Fatalf("expected *GatewayError, got %T: %v", err, err)
	}
	if ge.Code != "irreversible_action_denied" {
		t.Errorf("Code = %q, want %q", ge.Code, "irreversible_action_denied")
	}
	if ge.ResponseMeta.Reversibility != "irreversible" {
		t.Errorf("ResponseMeta.Reversibility = %q, want %q", ge.ResponseMeta.Reversibility, "irreversible")
	}
	if ge.ResponseMeta.PrincipalLevel != 4 {
		t.Errorf("ResponseMeta.PrincipalLevel = %d, want 4", ge.ResponseMeta.PrincipalLevel)
	}
	if !ge.ResponseMeta.BackupRecommended {
		t.Error("ResponseMeta.BackupRecommended should be true")
	}
}

func TestCallWithMetadata_NoHeaders(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  "ok",
			ID:      float64(1),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	cr, err := c.CallWithMetadata(context.Background(), "read", map[string]any{"path": "/tmp"})
	if err != nil {
		t.Fatalf("CallWithMetadata failed: %v", err)
	}

	// Default values when no headers present
	if cr.Meta.Reversibility != "" {
		t.Errorf("Reversibility = %q, want empty", cr.Meta.Reversibility)
	}
	if cr.Meta.BackupRecommended {
		t.Error("BackupRecommended should be false when header absent")
	}
	if cr.Meta.PrincipalLevel != -1 {
		t.Errorf("PrincipalLevel = %d, want -1 (unset)", cr.Meta.PrincipalLevel)
	}
}

func TestCallWithMetadata_Retries503(t *testing.T) {
	var attempts atomic.Int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		n := attempts.Add(1)
		if n <= 1 {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(503)
			json.NewEncoder(w).Encode(GatewayError{Code: "circuit_open"})
			return
		}
		w.Header().Set("X-Precinct-Reversibility", "reversible")
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  "ok",
			ID:      float64(1),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test",
		WithHTTPClient(srv.Client()),
		WithMaxRetries(3),
		WithBackoffBase(1*time.Millisecond),
		withSleepFunc(func(d time.Duration) {}),
	)

	cr, err := c.CallWithMetadata(context.Background(), "read", nil)
	if err != nil {
		t.Fatalf("CallWithMetadata failed: %v", err)
	}
	if cr.Meta.Reversibility != "reversible" {
		t.Errorf("Reversibility = %q, want %q", cr.Meta.Reversibility, "reversible")
	}
}

func TestParseResponseMeta(t *testing.T) {
	h := http.Header{}
	h.Set("X-Precinct-Reversibility", "costly_reversible")
	h.Set("X-Precinct-Backup-Recommended", "false")
	h.Set("X-Precinct-Principal-Level", "3")
	h.Set("X-Precinct-Principal-Role", "agent")
	h.Set("X-Precinct-Principal-Capabilities", "read, execute")
	h.Set("X-Precinct-Auth-Method", "header_declared")

	meta := parseResponseMeta(h)
	if meta.Reversibility != "costly_reversible" {
		t.Errorf("Reversibility = %q", meta.Reversibility)
	}
	if meta.BackupRecommended {
		t.Error("BackupRecommended should be false")
	}
	if meta.PrincipalLevel != 3 {
		t.Errorf("PrincipalLevel = %d, want 3", meta.PrincipalLevel)
	}
	if meta.PrincipalRole != "agent" {
		t.Errorf("PrincipalRole = %q, want agent", meta.PrincipalRole)
	}
	if len(meta.PrincipalCapabilities) != 2 {
		t.Errorf("PrincipalCapabilities = %v, want 2 items", meta.PrincipalCapabilities)
	}
	if meta.AuthMethod != "header_declared" {
		t.Errorf("AuthMethod = %q, want header_declared", meta.AuthMethod)
	}
}

// --- Unit Tests: Edge Cases ---

func TestCall_NilParams(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var req jsonRPCRequest
		json.NewDecoder(r.Body).Decode(&req)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(jsonRPCResponse{
			JSONRPC: "2.0",
			Result:  "ok",
			ID:      float64(req.ID),
		})
	}))
	defer srv.Close()

	c := NewClient(srv.URL, "spiffe://test", WithHTTPClient(srv.Client()))
	result, err := c.Call(context.Background(), "health", nil)
	if err != nil {
		t.Fatalf("Call with nil params failed: %v", err)
	}
	if result != "ok" {
		t.Errorf("result = %v, want 'ok'", result)
	}
}

func TestTruncate(t *testing.T) {
	cases := []struct {
		input  string
		maxLen int
		want   string
	}{
		{"short", 10, "short"},
		{"exactly10!", 10, "exactly10!"},
		{"this is longer than ten", 10, "this is lo..."},
		{"", 5, ""},
	}
	for _, tc := range cases {
		got := truncate(tc.input, tc.maxLen)
		if got != tc.want {
			t.Errorf("truncate(%q, %d) = %q, want %q", tc.input, tc.maxLen, got, tc.want)
		}
	}
}
